#!/usr/bin/env bash

readonly RKENDRIK_SITE_PATH=$HOME/rafaelkendrik.github.io

cd $RKENDRIK_SITE_PATH

git checkout -b deploy
git checkout deploy

$RKENDRIK_SITE_PATH/cli/rkendrik-compile
$RKENDRIK_SITE_PATH/cli/rkendrik-build

[ -d docs-deploy ] \
  && rm docs-deploy -rf \
  || cp docs docs-deploy -r

git add docs-deploy -f && git commit -m "Github Pages Deploy $(date '+%Y-%m-%d %H:%M:%S')"
git push origin `git subtree split --prefix docs-deploy deploy`:master --force

git checkout dev
git branch -D deploy
